os: Ubuntu
platform:
  - x64
install:
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
  - git submodule init
  - git submodule update
build_script:
  - cp -v vagrant/examples/Vagrantfile.capev2-box.ubuntu-2004.x86_64.example vagrant/Vagrantfile.capev2-box
  - sudo vagrant up --provider=libvirt capev2-box
  - sudo vagrant destroy --force capev2-box
on_success:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
  - sudo bash install.sh
  - nvm install lts/*
  - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
  - npx semantic-release
test: off
